REM call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
cmake -G "Ninja" ^
 -DTIGL_CREATOR=OFF ^
 -DTIGL_BINDINGS_PYTHON_INTERNAL=ON ^
 -DTIGL_CONCAT_GENERATED_FILES=ON ^
 -DCMAKE_INSTALL_PREFIX=install ^
 -DTIGL_BUILD_TESTS=OFF ^
 -DTIGL_NIGHTLY=OFF ^
 -DPython3_FIND_STRATEGY=LOCATION ^
 -DPython3_FIND_FRAMEWORK=NEVER ^
 -DTIGL_BINDINGS_PYTHON=ON ^
 -DTIGL_BINDINGS_MATLAB=OFF ^
 -DOCE_STATIC_LIBS=OFF ^
 ..
REM if errorlevel 1 exit 1